### PR TITLE
Subsequent calls generate new data

### PR DESCRIPTION
**Pull request by CucumisSativus**
Before this commit each and every call yields exactly the same result. Which was a cause of some problems for me. 

After this commit next call means new data. The only disadvantage of such an approach is introducing side effects to random method but on the other hand this is perfectly predictable.

I'm open for any suggestions :) And thanks for your hard work

### CODE REVIEW

**Comment by DanielaSfregola** [comment]
Hi @CucumisSativus,
thanks for your contribution!

My only concern is that having 1 seed per randomly generated data, will make impossible to easily replicate the whole testing session:
1) because we can only fix 1 seed using the RANDOM_DATA_GENERATOR_SEED variable
2) because it will be extremely difficult to understand which seed refers to which randomly generated data.

This is the reason why I have created random[T](n: Int) -- that generates a sequence of values of the same type that are different. But I have to admit is not a super ideal solution.

**Comment by DanielaSfregola** [comment]
I also thought of using the initial seed to generate a list of seeds, but then you need to guaranteed that the seeds are always applied in the same order -- but we cannot do that if the tests are run in parallel.

If you have any suggestions/ideas on how to improve this I'd love to hear them!

But unfortunately we were cannot get rid of the need of completely replicate a test session -- otherwise we lose the whole point of the library.

**Comment by CucumisSativus** [comment]
@DanielaSfregola thanks for your response. I belive that issues you addresses are more than valid and unfortunately i don't know how to solve them :(

Feel free to close this pull request, i'll stick to `random[T](n: Int)`. Thanks again for this library :)

**Comment by DanielaSfregola** [comment]
No worries @CucumisSativus, the pleasure is all mine.

Contribution and change proposals are always welcome!

I'll keep thinking about this problem...and maybe, how knows, one day we will find a better solution than `random[T](n: Int)`!

Cheers, 
Daniela

Closing PR without merging as requested.

**Pull request closed without merging**
